- name: Main playbook
  hosts: all
  become: yes
  roles:
    - role: geerlingguy.pip
  
  
- name: Deploy Redmine on servers
  hosts: all
  become: true
  roles:
    - redmine_deploy

- name: Instsall Datadog Agent on servers
  hosts: webservers
  roles:
    - { role: datadog.datadog, become: yes }    
  
       
