
- name: Copy file
  template:
    src:  ./templates/.env.j2
    dest: ~/.env
    mode: 0644
  tags:
   - refresh-params
   - deploy

- name: Deploy Redmine
  community.docker.docker_container:
    name: hexlet-redmine
    image: redmine
    ports:
      - "{{ porthost }}:{{ portcontainer }}"
    env_file: "~/.env"
    restart_policy: always
    detach: yes
  tags:
   - deploy

- name: Stop il container Docker
  docker_container:
    name: hexlet-redmine
    state: stopped
  tags:
    - refresh-params
      
- name: Start il container Docker
  docker_container:
    name: hexlet-redmine
    state: started
  tags:
    - refresh-params